### PR TITLE
Fix typo; add badges

### PR DESCRIPTION
**Pull request by bartelink**
Suggest changing Github releases to align with nuget package versions (or remove the release badge!)

### CODE REVIEW

**Comment by gkinsman** [comment]
Thanks! I replicated the Serilog.Sinks.Email repo largely for the build process - it seems that github releases are triggered on every build, whereas nuget deploys are triggered by a change in build version in the csproj. Hmm. 

I've set appveyor to now only build when code changes occur (and not readme's/build etc) which should reduce the version count. I wonder if that sink just removes versions from github's release page.

**Comment by bartelink** [comment]
Ah, OK. In that case, feel free to remove the releases badge (it seems to be 404ing for some reason). [IME](https://github.com/jet/jet.jsonnet.converters), going whole hog and tagging commits at source iff a release is warranted, then using[MinVer](https://github.com/adamralph/minver) and expressing releases in terms of those works very well, but that may just be overkill (in addition to losing alignment with other sink repos).

**Comment by gkinsman** [comment]
Yeah agreed there - I went down that route with [Typescriptr](https://github.com/gkinsman/Typescriptr) but wanted to be consistent with other sinks. Will likely just leave the release page of github empty and use nuget :).

Thanks for the badges!

**Comment by bartelink** [comment]
Ha, I see you already had them over there (I stole these [from myself over here](https://github.com/jet/equinox))!

**Comment by gkinsman** [comment]
Great artists steal right?! That last one just used this as a reference implementation of a bunch of nice stuff: https://github.com/michael-wolfenden/StarWarsNames.

**Pull request merged**
